# Nombre de la aplicación
spring.application.name=ecommerce-backend

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommercedb
spring.datasource.username=ecommerceuser
spring.datasource.password=ecommercepass
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (el ORM que habla con la base de datos)
# create-drop: borra y recrea las tablas al iniciar (solo en desarrollo)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=8080
